import React, { useState } from 'react';
import { SchoolReport } from '../data/adminMockData';
import { soundFx } from '../../../lib/audio';
import {
  FileText,
  Download,
  Printer,
  CheckCircle2,
  Calendar,
  Filter,
  Search,
  Sparkles,
  Building
} from 'lucide-react';

interface ReportsManagementViewProps {
  reports: SchoolReport[];
}

export const ReportsManagementView: React.FC<ReportsManagementViewProps> = ({ reports }) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  const handleDownloadReport = (rep: SchoolReport) => {
    soundFx.playSuccess();
    setDownloadSuccess(`Downloaded "${rep.title}" as ${rep.fileFormat}`);
    setTimeout(() => setDownloadSuccess(null), 3000);
  };

  const filteredReports = reports.filter(
    (r) => selectedCategory === 'All' || r.category === selectedCategory
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-100 dark:bg-purple-950 text-purple-800 dark:text-purple-300 text-xs font-bold uppercase tracking-wider mb-2">
            <FileText className="w-3.5 h-3.5" />
            DEO Government & School Compliance Ledger
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white">
            Official School Reports & Compliance Documents
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Verified Marks Cards, Midday Meal Audits & District Educational Office Circular Submissions
          </p>
        </div>

        <button
          onClick={() => {
            soundFx.playSuccess();
            window.print();
          }}
          className="px-4 py-2.5 bg-purple-600 hover:bg-purple-700 text-white font-extrabold text-xs rounded-2xl shadow transition flex items-center gap-2"
        >
          <Printer className="w-4 h-4" />
          <span>Print Complete Ledger</span>
        </button>
      </div>

      {downloadSuccess && (
        <div className="p-4 rounded-2xl bg-emerald-50 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-200 text-xs font-bold flex items-center gap-2 border border-emerald-300">
          <CheckCircle2 className="w-4 h-4 text-emerald-600" />
          <span>{downloadSuccess}</span>
        </div>
      )}

      {/* Category Tabs */}
      <div className="flex items-center gap-2 bg-white dark:bg-slate-900 p-2 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-x-auto">
        {['All', 'Academic', 'DEO Government', 'Compliance'].map((cat) => (
          <button
            key={cat}
            onClick={() => {
              soundFx.playClick();
              setSelectedCategory(cat);
            }}
            className={`px-4 py-2.5 rounded-xl text-xs font-extrabold transition whitespace-nowrap ${
              selectedCategory === cat
                ? 'bg-purple-600 text-white shadow'
                : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
            }`}
          >
            {cat} Reports
          </button>
        ))}
      </div>

      {/* Reports List */}
      <div className="space-y-4">
        {filteredReports.map((rep) => (
          <div
            key={rep.id}
            className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 hover:border-purple-300 transition"
          >
            <div className="space-y-1 max-w-2xl">
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-full bg-purple-100 dark:bg-purple-950 text-purple-700 dark:text-purple-300 text-[10px] font-black uppercase">
                  {rep.category}
                </span>
                <span className="text-[10px] font-mono text-slate-400 font-bold">
                  {rep.id}
                </span>
              </div>
              <h3 className="font-extrabold text-base text-slate-900 dark:text-white">
                {rep.title}
              </h3>
              <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                {rep.description}
              </p>
              <div className="text-[11px] text-slate-400 font-medium pt-1">
                Generated by {rep.generatedBy} on {rep.generatedDate}
              </div>
            </div>

            <div className="flex items-center gap-3 self-end md:self-center">
              <span className="px-3 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-300 text-xs font-black">
                ✓ Verified
              </span>
              <button
                onClick={() => handleDownloadReport(rep)}
                className="px-4 py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-purple-50 dark:hover:bg-purple-950 text-purple-700 dark:text-purple-300 font-extrabold text-xs rounded-2xl border border-slate-200 dark:border-slate-700 transition flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                <span>Export {rep.fileFormat}</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
